#!/usr/bin/env python

from __future__ import print_function
from acheron import Acheron
import logging
import sys

logging.basicConfig(
    filename='/var/log/acheron.log',
    filemode='a+',
    level=logging.DEBUG,
)

a = Acheron('/var/run/acheron.pid', stdout="/dev/stdout", stderr="/dev/stderr")

if not sys.argv[1:]:
    print('acheron: error: no command supplied', file=sys.stderr)
    sys.exit(1)

{
    'start': a.start,
    'stop': a.stop,
    'restart': a.restart,
    'force-reload': a.restart,
    'status': a.status
}[sys.argv[1]]()
